# Site settings
title: 匡松的博客
email: woyehaizaixiang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  匡松的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://woyehaizaixiang.github.io/ # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: Bi Ji

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
twitter: woyehaizaixiang
weibo: woyehaizaixiang
github: woyehaizaixiang
instagram: woyehaizaixiang
linkedin: woyehaizaixiang

# avatar and Favicon
avatar: /assets/img/avatar.jpg
favicon: /assets/img/avatar.jpg

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

